// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5858.prototypeshootbot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController shooterTopLeft;
    public static SpeedController shooterTopRight;
    public static SpeedController shooterBottomLeft;
    public static SpeedController shooterBottomRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        shooterTopLeft = new Spark(0);
        LiveWindow.addActuator("Shooter", "TopLeft", (Spark) shooterTopLeft);
        
        shooterTopRight = new Spark(2);
        LiveWindow.addActuator("Shooter", "TopRight", (Spark) shooterTopRight);
        
        shooterBottomLeft = new Spark(3);
        LiveWindow.addActuator("Shooter", "BottomLeft", (Spark) shooterBottomLeft);
        
        shooterBottomRight = new Spark(1);
        LiveWindow.addActuator("Shooter", "BottomRight", (Spark) shooterBottomRight);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
